version: '3'
services:
  wso2si:
    image: cassandra:4.0.12
    hostname: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
      - "7000:7000"
    environment:
      # - CASSANDRA_LISTEN_ADDRESS=10.160.0.2
      - CASSANDRA_RPC_ADDRESS=10.160.0.2
      - CASSANDRA_SEEDS=10.160.0.2
      - CASSANDRA_BROADCAST_ADDRESS=34.93.62.229
    networks:
      - local

networks:
  local:
    driver: bridge