version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
      - /home/gcpuser/elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elk

  logstash:
    image: logstash:8.12.2
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - /home/gcpuser/elk/logstash/logstash-sample.conf:/usr/share/logstash/pipeline/logstash.conf
      - /home/gcpuser/elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ls_data:/usr/share/logstash/data

    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - /home/gcpuser/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kb_data:/usr/share/kibana/data
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elastic_data:
  ls_data:
  kb_data:
