version: '3'
services:
  filebeat:
    user: root
    container_name: filebeat
    image: elastic/filebeat:8.12.2
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - /home/gcpuser/wso2carbon-logs/carbon.log:/usr/share/filebeat/mylog/carbon.log
      - /home/gcpuser/dockerized/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: filebeat -e -strict.perms=false
    stdin_open: true
    network_mode: bridge
    deploy:
      mode: global

  zookeeper:
    image: bitnami/zookeeper:3.6.3
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - local

  kafka:
    image: bitnami/kafka:3.0.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      - KAFKA_BROKER_ID: 1
      - KAFKA_LISTENERS: PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.5.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER: yes
    networks:
      - local

networks:
  local:
    driver: bridge