version: '3'
services:
  wso2si:
    image: ramilu90/wso2si:4.2.0
    hostname: wso2si
    container_name: wso2si
    ports:
      - "9443:9443"
    volumes:
      - /home/gcpuser/dockerized/si/files/siddhi-apps:/home/wso2carbon/wso2si-4.2.0/wso2/server/deployment/siddhi-files
      - /home/gcpuser/dockerized/si/files/deployment.toml:/home/wso2carbon/wso2si-4.2.0/conf/server/deployment.toml
      - /home/gcpuser/dockerized/si/lib:/home/wso2carbon/wso2si-4.2.0/lib
      - /home/gcpuser/dockerized/si/lib:/home/wso2carbon/wso2si-4.2.0/wso2/server/logs
    networks:
      - local

networks:
  local:
    driver: bridge