version: '3'
services:
  wso2si:
    image: docker.wso2.com/wso2si:4.2.0
    hostname: wso2si
    container_name: wso2si
    ports:
      - "9443:9443"
    volumes:
      - /home/gcpuser/si/asia/siddhi-apps:/home/wso2carbon/wso2si-4.2.0/wso2/server/deployment/siddhi-files
      - /home/gcpuser/si/asia/deployment.toml:/home/wso2carbon/wso2si-4.2.0/conf/server/deployment.toml
      - /home/gcpuser/si/lib:/home/wso2carbon/wso2si-4.2.0/lib
    networks:
      - kafka